const terms = 'These Terms and Conditions were updated and effective as of 14th of March 2016\
 <br/><br/>PLEASE READ THIS AGREEMENT CAREFULLY BEFORE USING THE IDENTALSOFT SERVICE, INCLUDING, WITHOUT LIMITATION, ALL CONTENT SUCH AS TEXT, INFORMATION, IMAGES, APPLICATIONS, TEMPLATES, SOFTWARE, FEATURES, UPDATES, AND OTHER INFORMATION, SERVICES AND MATERIALS (COLLECTIVELY, THE "SERVICE(S)"). BY ACCESSING OR USING ALL OR ANY PORTION OF THE SERVICE, YOU ACKNOWLEDGE YOUR ACCEPTANCE TO THESE IDENTALSOFT TERMS AND CONDITIONS, AS AMENDED FROM TIME TO TIME, ("AGREEMENT") AND REPRESENT THAT YOU ARE AUTHORIZED TO ENTER INTO THIS AGREEMENT ON BEHALF OF THE CUSTOMER. IF YOU DO NOT AGREE TO THE TERMS OF THIS AGREEMENT, IDENTALSOFT DOES NOT GRANT YOU THE RIGHT TO USE THE SERVICES, AND YOU MUST CEASE USE OF AND ACCESS TO THE SERVICES IMMEDIATELY.\
 <br/><br/>This Agreement is between iDentalSoft, Inc, a Delaware corporation with its principal place of business at 16 Corning Ave #140, Milpitas CA 95035 ("iDS") and you or the entity you represent ("You") and governs Your use of the Service.\
<br/><br/>1. Service Plans\
<br/><br/>The Service is available as a paid service with a limited number of licensed users ("Users") as specified on your order form ("Order Form"). Additional services are included as part of the paid service except where specified on the Order Form.\
<br/><br/>2. Payment\
<br/><br/>In consideration of the license granted hereunder, payment for Services shall be at prices and under terms stated on the Order Form, or as otherwise stated or quoted by iDS from time to time. All prices are exclusive of taxes, which may or may not be added to the price, depending on applicable law and your legal residence. You shall be responsible for any and all taxes related to this Agreement.\
<br/><br/>If payment by your credit card is denied, or your charge is returned to iDS for any reason, including charge-back or if you otherwise fails to make any payments owing to iDS, iDS may, at iDSs sole discretion, suspend or terminate your access to the Service and/or terminate this Agreement. Your right to use the Services are subject to any limits established by iDS or by the issuer of your credit card. Interest charges of 1% per month (or the highest rate permitted by law if lower than 1% per month) will accrue daily on any unpaid balance which is more than thirty (30) days overdue.\
<br/><br/>3. Right of Use\You and your Users are hereby granted a non-exclusive, nontransferable, right to use the Service, solely for your own internal business purposes, subject to this Agreement. All rights not expressly granted to You are reserved by iDS. Your right of use is at all times conditioned on compliance with the terms of this Agreement and your prompt and timely payment for the Service. Breach of any term of this Agreement, non-payment, or delay in payment shall terminate any right of use granted to the You and your Users under this Agreement.\
<br/><br/>You shall not: (i) license, sublicense, sell, resell, transfer, assign, distribute or otherwise commercially exploit or make available to any third party the Service in any way; (ii) modify or make derivative works based upon the Service; (iii) create Internet "links" to the Service or "frame" or "mirror" any content on any other server or wireless or Internet-based device; or (iv) reverse engineer or access the Service in order to (a) build a competitive product or service, (b) build a product using similar ideas, features, functions or graphics of the Service, or (c) copy any ideas, features, functions or graphics of the Service. You may use the Service only for your internal business purposes and shall not: (i) send spam or otherwise duplicative or unsolicited messages in violation of applicable laws; (ii) send or store infringing, obscene, threatening, libelous, or otherwise unlawful or tortuous material, including material harmful to children or violative of third party privacy rights; (iii) send or store material containing software viruses, worms, Trojan horses or other harmful computer code, files, scripts, agents or programs; (iv) interfere with or disrupt the integrity, bandwidth or performance of the Service or the data contained therein; (v) attempt to gain unauthorized access to the Service or its related systems or networks; or (vi) use the Service, including the content, intellectual property, technology, trademarks or service marks for any commercial purposes (i.e. soliciting customers, resale, etc.) without iDSs prior written consent.\
<br/><br/>4. Access\
<br/><br/>Access to the Service is available via a unique URL given at the time of registration, or via Software that you install on your own Server at the time of installation. The Service supports both full and mobile webpage formats. iDS will provide You and your User(s) with a username and password for accessing the Service. Usernames and passwords are personal, and are to be considered part of Confidential Information.\
<br/><br/>5. Your Responsibilities\
<br/><br/>You are responsible for all activity occurring under your and your Users account(s) and shall abide by all applicable local, state, national and foreign laws, treaties and regulations in connection with your use of the Service, including those related to data privacy, including but not limited to the Health Insurance Portability and Accountability Act, the Health Information Technology for Economic and Clinical Health Act (collectively referred to herein as "HIPAA"), Payment Card Industry Data Security Standards ("PCI DSS"), international communications and the transmission of technical or personal data. In addition, You are responsible for abiding by any and all internal policies, procedures and regulations, which are required, by your employer and/or the applicable administrators of your account. You shall: (i) notify iDS immediately of any unauthorized use of any password or account or any other known or suspected breach of security; (ii) report to iDS immediately and use reasonable efforts to stop immediately any copying or distribution of content that is known or suspected by You or others to violate this Agreement or the intellectual property rights of third parties; and (iii) not impersonate another user or provide false identity information to gain access to or use the Service. By accessing the Service, You represent and warrant that you have not falsely identified yourself nor provided any false information to gain access to the Service and that your billing information is correct.'

export default terms;