const terms = 'Các Điều khoản và Điều kiện này đã được cập nhật và có hiệu lực kể từ ngày 14 tháng 3 năm 2016\
 <br/><br/>VUI LÒNG ĐỌC KỸ THỎA THUẬN NÀY TRƯỚC KHI SỬ DỤNG DỊCH VỤ A DENTAL CLINIC, BAO GỒM, KHÔNG GIỚI HẠN, TẤT CẢ NỘI DUNG NHƯ VĂN BẢN, THÔNG TIN, HÌNH ẢNH, ỨNG DỤNG, NHÓM, PHẦN MỀM, TÍNH NĂNG, CẬP NHẬT VÀ CÁC THÔNG TIN, DỊCH VỤ VÀ TÀI LIỆU KHÁC ( S)"). BẰNG VIỆC TRUY CẬP HOẶC SỬ DỤNG TẤT CẢ HOẶC BẤT KỲ PHẦN NÀO CỦA DỊCH VỤ, BẠN XÁC NHẬN SỰ ĐỒNG Ý CỦA MÌNH VỚI CÁC ĐIỀU KHOẢN VÀ ĐIỀU KIỆN SẮC NÀY, NHƯ ĐƯỢC SỬA ĐỔI TỪ THỜI GIAN, ("THỎA THUẬN") VÀ TUYÊN BỐ RẰNG BẠN ĐƯỢC PHÉP THUỘC VÀO THỎA THUẬN NÀY VỀ KHÁCH HÀNG. NẾU BẠN KHÔNG ĐỒNG Ý VỚI CÁC ĐIỀU KHOẢN CỦA THỎA THUẬN NÀY, A DENTAL CLINIC KHÔNG CẤP CHO BẠN QUYỀN SỬ DỤNG DỊCH VỤ VÀ BẠN PHẢI SỬ DỤNG VÀ TRUY CẬP DỊCH VỤ NGAY LẬP TỨC.\
 <br/><br/>Thỏa thuận này là giữa A Dental Clinic, Inc, một tập đoàn Delaware có trụ sở kinh doanh chính tại 16 Corning Ave # 140, Milpitas CA 95035 ("ADC") và bạn hoặc pháp nhân mà bạn đại diện ("Bạn") và điều chỉnh việc bạn sử dụng Dịch vụ.\
<br/><br/>1. Kế hoạch Dịch vụ\
<br/><br/>Dịch vụ có sẵn dưới dạng dịch vụ trả phí với một số lượng hạn chế người dùng được cấp phép ("Người dùng") như được chỉ định trên biểu mẫu đặt hàng của bạn ("Mẫu đơn đặt hàng"). Các dịch vụ bổ sung được bao gồm như một phần của dịch vụ trả phí ngoại trừ trường hợp được chỉ định trên Mẫu đơn đặt hàng.\
<br/><br/>2. Thanh toán\
<br/><br/>Xem xét giấy phép được cấp dưới đây, thanh toán cho Dịch vụ sẽ theo giá và theo các điều khoản được nêu trên Biểu mẫu đặt hàng, hoặc theo cách khác được ADC tuyên bố hoặc trích dẫn vào từng thời điểm. Tất cả giá đều chưa bao gồm thuế, có thể thêm hoặc không vào giá, tùy thuộc vào luật hiện hành và nơi cư trú hợp pháp của bạn. Bạn sẽ chịu trách nhiệm về bất kỳ và tất cả các khoản thuế liên quan đến Thỏa thuận này.\
<br/><br/>Nếu thanh toán bằng thẻ tín dụng của bạn bị từ chối hoặc khoản phí của bạn được trả lại cho ADC vì bất kỳ lý do gì, bao gồm cả khoản bồi hoàn hoặc nếu bạn không thực hiện bất kỳ khoản thanh toán nào cho ADC, ADC có thể, theo quyết định riêng của ADC, tạm dừng hoặc chấm dứt quyền truy cập của bạn đối với Dịch vụ và / hoặc chấm dứt Thỏa thuận này. Quyền sử dụng Dịch vụ của bạn phải tuân theo mọi giới hạn do ADC hoặc tổ chức phát hành thẻ tín dụng của bạn thiết lập. Phí lãi suất 1% mỗi tháng (hoặc lãi suất cao nhất được pháp luật cho phép nếu thấp hơn 1% mỗi tháng) sẽ tích lũy hàng ngày trên bất kỳ số dư chưa thanh toán nào quá hạn trên ba mươi (30) ngày.\
<br/><br/>3. Quyền sử dụng\
<br/><br/>Bạn và Người dùng của bạn theo đây được cấp quyền sử dụng Dịch vụ không độc quyền, không thể chuyển nhượng, chỉ cho các mục đích kinh doanh nội bộ của riêng bạn, tuân theo Thỏa thuận này. Tất cả các quyền không được cấp rõ ràng cho Bạn đều được ADC bảo lưu. Quyền sử dụng của bạn luôn có điều kiện là tuân thủ các điều khoản của Thỏa thuận này và việc bạn thanh toán Dịch vụ nhanh chóng và kịp thời. Việc vi phạm bất kỳ điều khoản nào của Thỏa thuận này, không thanh toán hoặc chậm thanh toán sẽ chấm dứt mọi quyền sử dụng được cấp cho Bạn và Người dùng của bạn theo Thỏa thuận này.\
<br/><br/>Bạn không được: (i) cấp phép, cấp phép lại, bán, bán lại, chuyển nhượng, chuyển nhượng, phân phối hoặc khai thác thương mại hoặc cung cấp Dịch vụ cho bất kỳ bên thứ ba nào theo bất kỳ cách nào; (ii) sửa đổi hoặc tạo ra các sản phẩm phái sinh dựa trên Dịch vụ; (iii) tạo "liên kết" Internet đến Dịch vụ hoặc "khung" hoặc "phản chiếu" bất kỳ nội dung nào trên bất kỳ máy chủ nào khác hoặc thiết bị không dây hoặc dựa trên Internet; hoặc (iv) thiết kế đối chiếu hoặc truy cập Dịch vụ để (a) xây dựng sản phẩm hoặc dịch vụ cạnh tranh, (b) xây dựng sản phẩm bằng cách sử dụng các ý tưởng, tính năng, chức năng hoặc đồ họa tương tự của Dịch vụ, hoặc (c) sao chép bất kỳ ý tưởng nào, các tính năng, chức năng hoặc đồ họa của Dịch vụ. Bạn chỉ có thể sử dụng Dịch vụ cho các mục đích kinh doanh nội bộ của mình và không được: (i) gửi spam hoặc các tin nhắn trùng lặp hoặc không được yêu cầu vi phạm luật hiện hành; (ii) gửi hoặc lưu trữ tài liệu vi phạm, khiêu dâm, đe dọa, bôi nhọ, hoặc bất hợp pháp hoặc quanh co, bao gồm tài liệu có hại cho trẻ em hoặc vi phạm quyền riêng tư của bên thứ ba; (iii) gửi hoặc lưu trữ tài liệu có chứa vi rút phần mềm, sâu, ngựa Trojan hoặc mã máy tính có hại khác, tệp, tập lệnh, tác nhân hoặc chương trình; (iv) can thiệp hoặc phá vỡ tính toàn vẹn, băng thông hoặc hiệu suất của Dịch vụ hoặc dữ liệu có trong đó; (v) cố gắng truy cập trái phép vào Dịch vụ hoặc các hệ thống hoặc mạng liên quan của nó; hoặc (vi) sử dụng Dịch vụ, bao gồm nội dung, sở hữu trí tuệ, công nghệ, nhãn hiệu hoặc nhãn hiệu dịch vụ cho bất kỳ mục đích thương mại nào (tức là chào mời khách hàng, bán lại, v.v.) mà không có sự đồng ý trước bằng văn bản của ADC.\
<br/><br/>4. Truy cập\
<br/><br/>Quyền truy cập Dịch vụ khả dụng thông qua một URL duy nhất được cung cấp tại thời điểm đăng ký hoặc qua Phần mềm mà bạn cài đặt trên Máy chủ của riêng mình tại thời điểm cài đặt. Dịch vụ hỗ trợ cả định dạng trang web đầy đủ và di động. ADC sẽ cung cấp cho Bạn và (các) Người dùng của bạn tên người dùng và mật khẩu để truy cập Dịch vụ. Tên người dùng và mật khẩu là cá nhân và được coi là một phần của Thông tin bí mật.\
<br/><br/>5. Trách nhiệm\
<br/><br/>Bạn chịu trách nhiệm về tất cả các hoạt động xảy ra trong (các) tài khoản Người dùng của bạn và của bạn và sẽ tuân thủ tất cả các luật, hiệp ước và quy định hiện hành của địa phương, tiểu bang, quốc gia và nước ngoài liên quan đến việc bạn sử dụng Dịch vụ, bao gồm cả những quy định liên quan đến quyền riêng tư dữ liệu, bao gồm nhưng không giới hạn ở Đạo luật về trách nhiệm giải trình và cung cấp bảo hiểm y tế, Đạo luật về công nghệ thông tin y tế cho sức khỏe kinh tế và lâm sàng (được gọi chung ở đây là "HIPAA"), Tiêu chuẩn bảo mật dữ liệu ngành thẻ thanh toán ("PCI DSS"), truyền thông quốc tế và truyền dữ liệu kỹ thuật hoặc dữ liệu cá nhân. Ngoài ra, Bạn có trách nhiệm tuân thủ bất kỳ và tất cả các chính sách, thủ tục và quy định nội bộ, được yêu cầu bởi chủ lao động của bạn và / hoặc các quản trị viên hiện hành của tài khoản của bạn. Bạn phải: (i) thông báo cho ADC ngay lập tức về bất kỳ hành vi sử dụng trái phép nào đối với bất kỳ mật khẩu hoặc tài khoản nào hoặc bất kỳ hành vi vi phạm bảo mật nào đã biết hoặc bị nghi ngờ; (ii) báo cáo với ADC ngay lập tức và sử dụng các nỗ lực hợp lý để ngăn chặn ngay lập tức mọi hành vi sao chép hoặc phân phối nội dung mà Bạn hoặc những người khác biết hoặc nghi ngờ vi phạm Thỏa thuận này hoặc quyền sở hữu trí tuệ của bên thứ ba; và (iii) không mạo danh người dùng khác hoặc cung cấp thông tin nhận dạng sai lệch để có quyền truy cập hoặc sử dụng Dịch vụ. Bằng cách truy cập Dịch vụ, Bạn tuyên bố và đảm bảo rằng bạn không nhận dạng sai bản thân cũng như không cung cấp bất kỳ thông tin sai lệch nào để có quyền truy cập vào Dịch vụ và thông tin thanh toán của bạn là chính xác.\
<br/><br/>Tham khảo: <a href="https://www.identalsoft.com/privacy-policy" target="_blank">https://www.identalsoft.com/privacy-policy</a>.'

export default terms;